### ISSUE TITLE
ask for advice

### ISSUE THREAD

**Issue by zcdliuwei** [DaAnIV/FourierFromSVG#2]
Hello, I'm very interested in your work. What a wonderful display !!
Personally, Fourier seems to imitate the process of human painting, and all the examples you show can be drawn with one stroke.
I would like to ask if Fourier supports multiple strokes.
Suppose there are two butterflies in the original PNG image, or there are multiple paths in my SVG file,
I want to draw two butterflies with two strokes, because if one stroke is used, there will be a big jump between the two targets，
And even if there is only one target or path, I also want to use multiple strokes in order to simplify and not cause a lot of jumping details,
So in general, my question is how to control Fourier drawing so that it can support user-defined stroke number？
I'm looking forward to your answer，Thank you very much。

**Comment by DaAnIV** [comment]
I am sorry for the late response didn't really work on this ^^
But if you are still interested I can think of 2 ways to do this:
One is by interpolating the color of the path in the SVG to the stroke drawn by the fourier series and having the part of the jump be with an alpha=0, i.e. invisible
The other way which I think is much easier is if the SVG has multiple paths to draw each one using a seperate fourier series.
You can then draw them simultaneously or draw the first freeze the stroke to not disappear and move to the next series until you've drawn all paths

**Comment by zcdliuwei** [comment]
> I am sorry for the late response didn't really work on this ^^
> But if you are still interested I can think of 2 ways to do this:
> One is by interpolating the color of the path in the SVG to the stroke drawn by the fourier series and having the part of the jump be with an alpha=0, i.e. invisible
> The other way which I think is much easier is if the SVG has multiple paths to draw each one using a seperate fourier series.
> You can then draw them simultaneously or draw the first freeze the stroke to not disappear and move to the next series until you've drawn all paths

Thank you for your reply， I used the second method，helpful!
But I have another problem:  suppose there are two paths in SVG, A and B, which are disjoint but adjacent, when I wanted to simplify the two paths with fewer circles, the two paths that did not intersect became intersecting。
I don't know how to ensure that the two simplified paths are still disjoint，For example, add some kind of restriction？？

I'm looking forward to your answer，Thank you very much。

**Comment by DaAnIV** [comment]
I am not sure you can really restrict this. 
Each path is converted to a function and the fourier series does an approximation of that function and when it plays it just draws the approximation. 
Maybe if you increase the distance it will not intersect or add some sort of restriction to not draw in an area given by the 2nd path but I think to implement this it will require quite a bit of complicated logic.

If I'll have any more ideas I'll try to help and anyway would like to see the work you've done when it is ready :)
