### ISSUE TITLE
ModuleNotFoundError: No module named 'svgpathtools.svg2paths'

### ISSUE THREAD

**Issue by borekl** [DaAnIV/FourierFromSVG#3]
Installed the requirements with `pip3 install -r requirements`, run it as `FLASK_APP=main.py flask run` but I get a traceback that ends with:

    ModuleNotFoundError: No module named 'svgpathtools.svg2paths'

Module svgpathtools _is_ installed. Sorry if it's something trivial.

**Comment by chadleong** [comment]
Make the following change in svg2paths_ext.py

`from svgpathtools.svg2paths `

to

`from svgpathtools.svg_to_paths`

Created a MR  #4
